import Head from 'next/head';

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_API_KEY);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="bg-slate-300 font-serif text-5xl">Hello Mom</h1>
      </main>
    </>
  );
}
